import { useState } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { useTranslation } from 'react-i18next';
import { supabase } from '@/integrations/supabase/client';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from '@/components/ui/form';
import { Loader2 } from 'lucide-react';
import { toast } from 'sonner';

interface CreateClubDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  onSuccess: () => void;
}

export function CreateClubDialog({ open, onOpenChange, onSuccess }: CreateClubDialogProps) {
  const { t } = useTranslation();
  const [isLoading, setIsLoading] = useState(false);

  const createClubSchema = z.object({
    name: z.string().min(2, t('validation.club_name_min')).max(50),
    description: z.string().max(200).optional(),
  });

  type CreateClubFormData = z.infer<typeof createClubSchema>;

  const form = useForm<CreateClubFormData>({
    resolver: zodResolver(createClubSchema),
    defaultValues: { name: '', description: '' },
  });

  const onSubmit = async (data: CreateClubFormData) => {
    setIsLoading(true);
    
    // Need to provide invite_code as empty string, trigger will generate it
    const { error } = await supabase
      .from('clubs')
      .insert({
        name: data.name,
        description: data.description || null,
        invite_code: '', // Will be auto-generated by trigger
      });

    setIsLoading(false);

    if (error) {
      toast.error(t('club.create_failed') + ': ' + error.message);
      return;
    }

    toast.success(t('club.created_success'));
    form.reset();
    onOpenChange(false);
    onSuccess();
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-md bg-card border-border/50">
        <DialogHeader>
          <DialogTitle className="text-gold-gradient">{t('club.create')}</DialogTitle>
          <DialogDescription>
            {t('club.create_description')}
          </DialogDescription>
        </DialogHeader>
        
        <Form {...form}>
          <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-4">
            <FormField
              control={form.control}
              name="name"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>{t('club.name')}</FormLabel>
                  <FormControl>
                    <Input 
                      placeholder={t('club.name_placeholder')}
                      className="bg-input/50 border-border/50"
                      {...field} 
                    />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />
            <FormField
              control={form.control}
              name="description"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>{t('club.description_label')}</FormLabel>
                  <FormControl>
                    <Textarea 
                      placeholder={t('club.description_placeholder')}
                      className="bg-input/50 border-border/50 resize-none"
                      rows={3}
                      {...field} 
                    />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />
            <div className="flex gap-3 pt-2">
              <Button 
                type="button" 
                variant="outline" 
                className="flex-1"
                onClick={() => onOpenChange(false)}
              >
                {t('common.cancel')}
              </Button>
              <Button 
                type="submit" 
                className="flex-1 glow-gold" 
                disabled={isLoading}
              >
                {isLoading ? (
                  <><Loader2 className="mr-2 h-4 w-4 animate-spin" /> {t('common.creating')}</>
                ) : (
                  t('club.create')
                )}
              </Button>
            </div>
          </form>
        </Form>
      </DialogContent>
    </Dialog>
  );
}
