-- Add default event and tournament settings to clubs table
ALTER TABLE clubs ADD COLUMN IF NOT EXISTS default_event_time TEXT DEFAULT '19:00';
ALTER TABLE clubs ADD COLUMN IF NOT EXISTS default_max_tables INTEGER DEFAULT 1;
ALTER TABLE clubs ADD COLUMN IF NOT EXISTS default_seats_per_table INTEGER DEFAULT 10;
ALTER TABLE clubs ADD COLUMN IF NOT EXISTS default_buy_in_amount INTEGER DEFAULT 20;
ALTER TABLE clubs ADD COLUMN IF NOT EXISTS default_starting_chips INTEGER DEFAULT 10000;
ALTER TABLE clubs ADD COLUMN IF NOT EXISTS default_rebuy_amount INTEGER DEFAULT 20;
ALTER TABLE clubs ADD COLUMN IF NOT EXISTS default_rebuy_chips INTEGER DEFAULT 10000;
ALTER TABLE clubs ADD COLUMN IF NOT EXISTS default_addon_amount INTEGER DEFAULT 10;
ALTER TABLE clubs ADD COLUMN IF NOT EXISTS default_addon_chips INTEGER DEFAULT 5000;
ALTER TABLE clubs ADD COLUMN IF NOT EXISTS default_allow_rebuys BOOLEAN DEFAULT true;
ALTER TABLE clubs ADD COLUMN IF NOT EXISTS default_allow_addons BOOLEAN DEFAULT true;
ALTER TABLE clubs ADD COLUMN IF NOT EXISTS default_rebuy_until_level INTEGER DEFAULT 4;
ALTER TABLE clubs ADD COLUMN IF NOT EXISTS default_level_duration INTEGER DEFAULT 15;